---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease-base.yaml
  - helmrelease-istiod.yaml
  - helmrelease-gateway.yaml
  - peer-authentication.yaml
  - gateway.yaml
  - authorization-policy-default.yaml
  - network-policies/default-deny.yaml
  - network-policies/allow-istiod.yaml
  - network-policies/allow-gateway.yaml
