---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sre-worker.fullname" . }}
  labels:
    {{- include "sre-worker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.app.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sre-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sre-worker.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "sre-worker.serviceAccountName" . }}
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          {{- with .Values.app.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.serviceMonitor.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.serviceMonitor.port }}
              protocol: TCP
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: {{ .Values.app.resources.requests.cpu }}
              memory: {{ .Values.app.resources.requests.memory }}
            limits:
              cpu: {{ .Values.app.resources.limits.cpu }}
              memory: {{ .Values.app.resources.limits.memory }}
          livenessProbe:
            exec:
              command:
                {{- toYaml .Values.app.probes.liveness.exec.command | nindent 16 }}
            initialDelaySeconds: {{ .Values.app.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.liveness.periodSeconds }}
          readinessProbe:
            exec:
              command:
                {{- toYaml .Values.app.probes.readiness.exec.command | nindent 16 }}
            initialDelaySeconds: {{ .Values.app.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.readiness.periodSeconds }}
          env:
            {{- range .Values.app.env }}
            {{- if .value }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- if .secretRef }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretRef }}
                  key: value
            {{- end }}
            {{- end }}
