---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-env-values
  namespace: logging
data:
  values.yaml: |
    loki:
      commonConfig:
        path_prefix: /tmp/loki
      storage:
        filesystem:
          chunks_directory: /tmp/loki/chunks
          rules_directory: /tmp/loki/rules
      rulerConfig:
        storage:
          local:
            directory: /tmp/loki/rules
    singleBinary:
      persistence:
        enabled: false
      extraVolumeMounts:
        - name: data
          mountPath: /tmp/loki
      extraVolumes:
        - name: data
          emptyDir: {}
