---
# Generated for end-to-end test
all:
  children:
    control_plane:
      hosts:
        cp-1:
          ansible_host: 192.168.2.91
    workers:
      hosts:
        worker-1:
          ansible_host: 192.168.2.89
        worker-2:
          ansible_host: 192.168.2.92
  vars:
    ansible_user: sre-admin
    ansible_ssh_private_key_file: /home/vscode/.ssh/sre-proxmox-lab
