---
# Control plane specific variables
# Note: rke2_server_url is computed automatically by install-rke2.yml

rke2_tls_san:
  - "{{ ansible_facts['default_ipv4']['address'] | default('127.0.0.1') }}"
