---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease-loki.yaml
  - helmrelease-alloy.yaml
  - grafana-datasource.yaml
  - network-policies/default-deny.yaml
  - network-policies/allow-logging.yaml
