---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease.yaml
  - virtualservice.yaml
  - destinationrule.yaml
  - peerauthentication.yaml
  - network-policies/default-deny.yaml
  - network-policies/allow-neuvector.yaml
