---
galaxy_info:
  role_name: rke2_agent
  author: "SRE Platform Team"
  description: "RKE2 agent (worker) node installation and cluster join"
  license: "Apache-2.0"
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"

dependencies: []
